### ISSUE TITLE
Face ID does not work as expected

### ISSUE THREAD

**Issue by scriptPilot** [danielsogl/capacitor-face-id#14]
When I call auth() it works well the first time. But when I call it again after the user left and came back to the app, the authentication is done automatically, even if my face is not in the front of the camera anymore. How can I force to to the check properly?

**Comment by mkw2000** [comment]
I am experiencing this as well.

**Comment by scriptPilot** [comment]
@danielsogl - Is there any option to force the Face ID check on each auth() call?

**Comment by mkw2000** [comment]
@scriptPilot @danielsogl  I am going to look into this today

**Comment by mkw2000** [comment]
@danielsogl I submitted a PR with changes that fixed this issue for me when you get a chance
